### ISSUE TITLE
Ошибка java.sql.SQLFeatureNotSupportedException при старте приложения

### ISSUE THREAD

**Issue by AVPGenium** [ALVirtualTech/PetSearchBackend#19]
Лог прилагается.
Ошибка "java.sql.SQLFeatureNotSupportedException: Метод org.postgresql.jdbc.PgConnection.createClob() ещё не реализован" падает при старте приложения

**Comment by a-poliakov** [comment]
ошибка решается изменением properties (возможно, актуально только для spring boot 2+, а раньше значение по умолчанию было true):

`spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true`

**Comment by a-poliakov** [comment]
Решение:
1. https://github.com/spring-projects/spring-boot/issues/12007#issuecomment-369388646%23issuecomment-369388646
2. https://github.com/pgjdbc/pgjdbc/issues/1102
