### ISSUE TITLE
Разработка rest-api для авторизации (frontend + backend)

### ISSUE THREAD

**Issue by AVPGenium** [ALVirtualTech/PetSearchBackend#8]
Необходимо реализовать:
- [ ] методы авторизации + сериализация/десериализацию передаваемых данных в Google Protocol Buffers. 
- [ ] Добавить поддержку безопасного соединения по https.
- [x] интегрировать с Spring Security на backend-е

Для регистрации пользователя создать метод register. Для авторизации использовать метод login из spring security.

**Comment by a-poliakov** [comment]
в первой версии не используем GPB, авторизация по rest с authKey. Используем куки и кэш сессий на бекенде.
